In [537]:
import pandas as pd
import numpy as np

In [538]:
df=pd.read_csv("airline_flight_operations.csv")

In [539]:
df.head(10)

,flight_id,airline,flight_date,origin,destination,scheduled_departure,actual_departure,scheduled_arrival,actual_arrival,departure_delay,...,cancelled,cancellation_reason,flight_distance_km,aircraft_type,passengers,baggage_count,weather_condition,airport_congestion,ticket_price,status
0,FLT106794,Vistara,2025-05-11,Delhi,Kolkata,2025-05-11 14:59,2025-05-11 15:34,2025-05-11 16:24,2025-05-11 16:59,35,...,0,NaN,3419,A330,235.0,163,Cloudy,Medium,67563.39,Delayed
1,FLT101782,Air India,2024-04-25,Chennai,Ahmedabad,2024-04-25 19:33,2024-04-25 19:13,2024-04-25 20:54,2024-04-25 20:29,-20,...,0,NaN,5526,A320,217.0,148,Clear,Medium,20838.31,On Time
2,FLT108080,Air India,2025-03-24,Delhi,Frankfurt,2025-03-24 05:19,2025-03-24 06:10,2025-03-24 11:45,2025-03-24 12:34,51,...,0,NaN,4679,A330,132.0,267,Fog,Medium,83779.98,Delayed
3,FLT104003,British Airways,2025-03-01,Bengaluru,Kolkata,2025-03-01 22:39,2025-03-01 23:50,2025-03-02 02:37,2025-03-02 03:33,71,...,0,NaN,4004,A320,305.0,207,Cloudy,Medium,73415.62,Delayed
4,FLT103000,Vistara,2025-01-14,Kolkata,Mumbai,2025-01-14 22:19,2025-01-14 22:32,2025-01-15 06:11,2025-01-15 07:14,13,...,0,NaN,8630,A330,322.0,199,Fog,Low,53643.58,Severely Delayed
5,FLT102763,Air India,2025-05-14,Hyderabad,Chennai,2025-05-14 07:49,2025-05-14 07:49,2025-05-14 15:44,2025-05-14 16:10,0,...,0,NaN,6617,B777,91.0,172,Rain,Low,59091.17,Delayed
6,FLT103257,IndiGo,2025-01-04,Ahmedabad,Hyderabad,2025-01-04 14:45,2025-01-04 14:45,2025-01-04 16:22,2025-01-04 16:15,0,...,0,NaN,4828,B787,190.0,171,Rain,Medium,66869.54,On Time
7,FLT104867,SpiceJet,2024-05-26,Delhi,Dubai,2024-05-26 07:00,2024-05-26 07:30,2024-05-26 10:14,2024-05-26 10:28,30,...,TRUE,NaN,2548,A321,107.0,70,Clear,Low,68290.92,On Time
8,FLT104187,Air India,2024-01-14,Mumbai,Doha,2024-01-14 12:35,2024-01-14 12:24,2024-01-14 16:38,2024-01-14 16:39,-11,...,0,NaN,1744,B787,125.0,19,Rain,Medium,55280.99,On Time
9,FLT100658,SpiceJet,28/05/2025,Delhi,Hyderabad,2025-05-28 08:25,2025-05-28 08:28,2025-05-28 12:38,2025-05-28 13:16,3,...,1,Weather,6040,A350,104.0,279,Cloudy,Medium,73808.92,Cancelled

In [540]:
df.isnull().sum()

flight_id                 8
airline                  45
flight_date              35
origin                   29
destination              31
scheduled_departure      25
actual_departure         30
scheduled_arrival         0
actual_arrival            0
departure_delay           0
arrival_delay             0
cancelled                 0
cancellation_reason    8114
flight_distance_km        0
aircraft_type            25
passengers               35
baggage_count             0
weather_condition        40
airport_congestion        0
ticket_price             30
status                    0
dtype: int64

In [541]:
df=df.dropna(subset=["flight_id"])

In [542]:
df.shape

(8592, 21)

In [543]:
df.duplicated().sum()

np.int64(100)

In [544]:
df.drop_duplicates()

,flight_id,airline,flight_date,origin,destination,scheduled_departure,actual_departure,scheduled_arrival,actual_arrival,departure_delay,...,cancelled,cancellation_reason,flight_distance_km,aircraft_type,passengers,baggage_count,weather_condition,airport_congestion,ticket_price,status
0,FLT106794,Vistara,2025-05-11,Delhi,Kolkata,2025-05-11 14:59,2025-05-11 15:34,2025-05-11 16:24,2025-05-11 16:59,35,...,0,NaN,3419,A330,235.0,163,Cloudy,Medium,67563.39,Delayed
1,FLT101782,Air India,2024-04-25,Chennai,Ahmedabad,2024-04-25 19:33,2024-04-25 19:13,2024-04-25 20:54,2024-04-25 20:29,-20,...,0,NaN,5526,A320,217.0,148,Clear,Medium,20838.31,On Time
2,FLT108080,Air India,2025-03-24,Delhi,Frankfurt,2025-03-24 05:19,2025-03-24 06:10,2025-03-24 11:45,2025-03-24 12:34,51,...,0,NaN,4679,A330,132.0,267,Fog,Medium,83779.98,Delayed
3,FLT104003,British Airways,2025-03-01,Bengaluru,Kolkata,2025-03-01 22:39,2025-03-01 23:50,2025-03-02 02:37,2025-03-02 03:33,71,...,0,NaN,4004,A320,305.0,207,Cloudy,Medium,73415.62,Delayed
4,FLT103000,Vistara,2025-01-14,Kolkata,Mumbai,2025-01-14 22:19,2025-01-14 22:32,2025-01-15 06:11,2025-01-15 07:14,13,...,0,NaN,8630,A330,322.0,199,Fog,Low,53643.58,Severely Delayed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8595,FLT107192,Vistara,2025-04-17,Pune,Hyderabad,2025-04-17 18:08,2025-04-17 18:22,2025-04-18 02:06,2025-04-18 02:30,14,...,0,NaN,6412,B777,174.0,122,Clear,Low,7844.03,Delayed
8596,FLT104848,Vistara,2024-04-03,Pune,Ahmedabad,2024-04-03 14:32,2024-04-03 14:59,2024-04-03 21:36,2024-04-03 21:50,27,...,1,Security,5363,A350,161.0,210,Cloudy,Low,40307.52,Cancelled
8597,FLT103912,Air India,2024-05-19,Bengaluru,Chennai,2024-05-19 06:15,2024-05-19 06:24,2024-05-19 10:47,2024-05-19 10:56,9,...,0,NaN,5749,B787,223.0,89,Rain,Medium,8745.5,On Time
8598,FLT103768,Emirates,2024-11-14,Kolkata,Singapore,2024-11-14 12:27,2024-11-14 12:58,2024-11-14 17:15,2024-11-14 18:13,31,...,0,NaN,5250,B737,291.0,29,Cloudy,Medium,51030.73,Delayed
8599,FLT105139,Lufthansa,2025-04-23,Delhi,Singapore,23-04-2025 08:55,2025-04-23 08:52,2025-04-23 18:22,2025-04-23 18:35,-3,...,0,NaN,8771,ATR72,203.0,225,Cloudy,Medium,19710.62,On Time

In [545]:
df["airline"].unique()

array(['Vistara', 'Air India', 'British Airways', 'IndiGo', 'SpiceJet',
       'Akasa Air', 'Lufthansa', 'Qatar Airways', 'Akasa Air ',
       'Singapore Airlines', 'spicejet', 'Emirates', nan, 'SPICEJET',
       'Vistara ', 'IndiGo ', 'vistara', 'AirIndia', 'air india',
       ' SpiceJet ', 'AKASA AIR', 'akasa air', 'Emirates ',
       'British Airways ', 'Qatar Airways ', ' Air India ',
       'Singapore Airlines ', 'Air India ', 'AIR INDIA', 'INDIGO',
       'indigo', 'Lufthansa ', 'AkasaAir', 'SpiceJet ', 'VISTARA',
       ' Indigo', 'Spice Jet'], dtype=object)

In [546]:
df["airline"]=(df["airline"].str.strip().str.title())

In [547]:
df["airline"]=(df["airline"].str.strip().replace({"Airindia" : "Air India",
                                                 "Akasaair" : "Akasa Air",
                                                 "Spicejet" : "Spice Jet"}))

In [548]:
df["airline"].unique()

array(['Vistara', 'Air India', 'British Airways', 'Indigo', 'Spice Jet',
       'Akasa Air', 'Lufthansa', 'Qatar Airways', 'Singapore Airlines',
       'Emirates', nan], dtype=object)

In [549]:
df["origin"].unique()

array(['Delhi', 'Chennai', 'Bengaluru', 'Kolkata', 'Hyderabad',
       'Ahmedabad', 'Mumbai', 'Jaipur', 'MUMBAI', 'DELHI', 'Pune',
       'Chandigarh', 'CHENNAI', 'Chandigarh ', ' Chennai ', nan,
       'Jaipur ', 'Chennai ', 'Kolkata ', ' Hyderabad ', 'bengaluru',
       ' Delhi ', 'Bengaluru ', 'Ahmedabad ', 'Pune ', 'Mumbai ',
       'hyderabad', 'Hyderabad ', 'BANGALORE', 'mumbai', ' Mumbai ',
       'chennai', 'HYDERABAD', 'delhi', 'Delhi '], dtype=object)

In [550]:
df["origin"]=(df["origin"].str.strip().replace({
    "Bangluru" : "Bengaluru"}))

In [551]:
df["destination"].unique()

array(['Kolkata', 'Ahmedabad', 'Frankfurt', 'Mumbai', 'Chennai ',
       'Hyderabad', 'Dubai', 'Doha', 'Chennai', 'Jaipur', 'London',
       'Pune', 'Singapore', 'Frankfurt ', 'Bengaluru', 'BANGALORE',
       'Chandigarh', 'HYDERABAD', 'delhi', 'Hyderabad ', 'bengaluru', nan,
       'MUMBAI', 'Jaipur ', 'Doha ', ' Chennai ', 'Kolkata ',
       'Chandigarh ', 'hyderabad', ' Delhi ', 'chennai', 'London ',
       'CHENNAI', 'Dubai ', 'Pune ', 'Bengaluru ', ' Mumbai ',
       'Ahmedabad ', 'DELHI', 'Mumbai ', 'Singapore ', ' Hyderabad ',
       'mumbai'], dtype=object)

In [552]:
df["destination"]=(df["destination"].str.strip().str.title())

In [553]:
df["destination"]=(df["destination"].str.strip().replace({
    "Bangalore" : "Bengaluru"}))

In [554]:
df.isnull().sum()

flight_id                 0
airline                  45
flight_date              35
origin                   29
destination              31
scheduled_departure      25
actual_departure         29
scheduled_arrival         0
actual_arrival            0
departure_delay           0
arrival_delay             0
cancelled                 0
cancellation_reason    8107
flight_distance_km        0
aircraft_type            25
passengers               35
baggage_count             0
weather_condition        40
airport_congestion        0
ticket_price             30
status                    0
dtype: int64

In [555]:
df["cancelled"].unique()

array(['0', ' TRUE ', '1', 'yes', 'no', 'No', ' FALSE ', 'Yes'],
      dtype=object)

In [556]:
df[df["cancellation_reason"].isna()][["cancelled","cancellation_reason"]].head()

  cancelled cancellation_reason
0         0                 NaN
1         0                 NaN
2         0                 NaN
3         0                 NaN
4         0                 NaN

In [557]:
df.loc[(df["cancelled"]==False) & (df["cancellation_reason"].isna()),"cancellation_reason"]="Not Cancelled"

In [558]:
df.loc[(df["cancelled"]==True) & (df["cancellation_reason"].isna()),"cancellation_reason"]="Unknown"

In [559]:
df["cancellation_reason"].unique()

array([nan, 'Weather', 'Technical Issue', 'Operational Issue',
       'Crew Shortage', 'Security', 'Other', 'Airport Congestion'],
      dtype=object)

In [560]:
df.isnull().sum()

flight_id                 0
airline                  45
flight_date              35
origin                   29
destination              31
scheduled_departure      25
actual_departure         29
scheduled_arrival         0
actual_arrival            0
departure_delay           0
arrival_delay             0
cancelled                 0
cancellation_reason    8107
flight_distance_km        0
aircraft_type            25
passengers               35
baggage_count             0
weather_condition        40
airport_congestion        0
ticket_price             30
status                    0
dtype: int64

In [561]:
df["aircraft_type"]=df["aircraft_type"].str.strip()

In [562]:
df["aircraft_type"]=df["aircraft_type"].fillna("Unknown")

In [563]:
df["aircraft_type"].unique()

array(['A330', 'A320', 'B777', 'B787', 'A321', 'A350', 'B737', 'ATR72',
       'Unknown'], dtype=object)

In [564]:
df.isnull().sum()

flight_id                 0
airline                  45
flight_date              35
origin                   29
destination              31
scheduled_departure      25
actual_departure         29
scheduled_arrival         0
actual_arrival            0
departure_delay           0
arrival_delay             0
cancelled                 0
cancellation_reason    8107
flight_distance_km        0
aircraft_type             0
passengers               35
baggage_count             0
weather_condition        40
airport_congestion        0
ticket_price             30
status                    0
dtype: int64

In [565]:
df["passengers"]=pd.to_numeric(df["passengers"],errors="coerce")

In [566]:
df["passengers"]=df["passengers"].fillna(df["passengers"].median())
df["passengers"]=df["passengers"].astype(int)

In [567]:
df.isnull().sum()

flight_id                 0
airline                  45
flight_date              35
origin                   29
destination              31
scheduled_departure      25
actual_departure         29
scheduled_arrival         0
actual_arrival            0
departure_delay           0
arrival_delay             0
cancelled                 0
cancellation_reason    8107
flight_distance_km        0
aircraft_type             0
passengers                0
baggage_count             0
weather_condition        40
airport_congestion        0
ticket_price             30
status                    0
dtype: int64

In [568]:
df["weather_condition"].unique()

array(['Cloudy', 'Clear', 'Fog', 'Rain', 'Storm', 'Windy', 'Windy ',
       'Rain ', nan, 'Cloudy ', 'Clear ', 'Fog ', 'Storm '], dtype=object)

In [569]:
df["weather_condition"]=(df["weather_condition"].str.strip().str.title())

In [570]:
df["weather_condition"]=df["weather_condition"].fillna("Unknown")

In [571]:
df["ticket_price"]=pd.to_numeric(df["ticket_price"],errors="coerce")

In [572]:
df["ticket_price"]=df["ticket_price"].fillna(df["ticket_price"].median())
df["ticket_price"]=df["ticket_price"].astype(int)

In [573]:
df["ticket_price"].unique()

array([67563, 20838, 83779, ...,  8745, 51030, 19710], shape=(8007,))

In [574]:
df["airline"]=df["airline"].fillna("Unknown")
df["origin"]=df["origin"].fillna("Unknown")
df["destination"]=df["destination"].fillna("Unknown")

In [575]:
df.isnull().sum()

flight_id                 0
airline                   0
flight_date              35
origin                    0
destination               0
scheduled_departure      25
actual_departure         29
scheduled_arrival         0
actual_arrival            0
departure_delay           0
arrival_delay             0
cancelled                 0
cancellation_reason    8107
flight_distance_km        0
aircraft_type             0
passengers                0
baggage_count             0
weather_condition         0
airport_congestion        0
ticket_price              0
status                    0
dtype: int64

In [576]:
df["cancellation_reason"].unique()

array([nan, 'Weather', 'Technical Issue', 'Operational Issue',
       'Crew Shortage', 'Security', 'Other', 'Airport Congestion'],
      dtype=object)

In [577]:
df["cancelled"].unique()

array(['0', ' TRUE ', '1', 'yes', 'no', 'No', ' FALSE ', 'Yes'],
      dtype=object)

In [578]:
df["cancelled"]=(df["cancelled"].str.strip().str.title().replace({
    "1" : True,
    "True" : True,
    "Yes" : True,
    "0" : False,
    "No" : False,
    "False" : False}))

C:\Users\p3175\AppData\Local\Temp\ipykernel_3844\1639803555.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["cancelled"]=(df["cancelled"].str.strip().str.title().replace({

In [579]:
df.isnull().sum()

flight_id                 0
airline                   0
flight_date              35
origin                    0
destination               0
scheduled_departure      25
actual_departure         29
scheduled_arrival         0
actual_arrival            0
departure_delay           0
arrival_delay             0
cancelled                 0
cancellation_reason    8107
flight_distance_km        0
aircraft_type             0
passengers                0
baggage_count             0
weather_condition         0
airport_congestion        0
ticket_price              0
status                    0
dtype: int64

In [580]:
df.duplicated().sum()

np.int64(100)

In [581]:
df = df.drop_duplicates()

In [582]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8492 entries, 0 to 8599
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   flight_id            8492 non-null   object
 1   airline              8492 non-null   object
 2   flight_date          8457 non-null   object
 3   origin               8492 non-null   object
 4   destination          8492 non-null   object
 5   scheduled_departure  8467 non-null   object
 6   actual_departure     8463 non-null   object
 7   scheduled_arrival    8492 non-null   object
 8   actual_arrival       8492 non-null   object
 9   departure_delay      8492 non-null   object
 10  arrival_delay        8492 non-null   object
 11  cancelled            8492 non-null   bool
 12  cancellation_reason  481 non-null    object
 13  flight_distance_km   8492 non-null   int64
 14  aircraft_type        8492 non-null   object
 15  passengers           8492 non-null   int64
 16  baggage_count        8492 non-null   int64
 17  weather_condition    8492 non-null   object
 18  airport_congestion   8492 non-null   object
 19  ticket_price         8492 non-null   int64
 20  status               8492 non-null   object
dtypes: bool(1), int64(4), object(16)
memory usage: 1.4+ MB

In [583]:
df["cancellation_reason"].unique()

array([nan, 'Weather', 'Technical Issue', 'Operational Issue',
       'Crew Shortage', 'Security', 'Other', 'Airport Congestion'],
      dtype=object)

In [584]:
df.loc[:,"cancellation_reason"]=df["cancellation_reason"].fillna("Unknown")

In [585]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8492 entries, 0 to 8599
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   flight_id            8492 non-null   object
 1   airline              8492 non-null   object
 2   flight_date          8457 non-null   object
 3   origin               8492 non-null   object
 4   destination          8492 non-null   object
 5   scheduled_departure  8467 non-null   object
 6   actual_departure     8463 non-null   object
 7   scheduled_arrival    8492 non-null   object
 8   actual_arrival       8492 non-null   object
 9   departure_delay      8492 non-null   object
 10  arrival_delay        8492 non-null   object
 11  cancelled            8492 non-null   bool
 12  cancellation_reason  8492 non-null   object
 13  flight_distance_km   8492 non-null   int64
 14  aircraft_type        8492 non-null   object
 15  passengers           8492 non-null   int64
 16  baggage_count        8492 non-null   int64
 17  weather_condition    8492 non-null   object
 18  airport_congestion   8492 non-null   object
 19  ticket_price         8492 non-null   int64
 20  status               8492 non-null   object
dtypes: bool(1), int64(4), object(16)
memory usage: 1.4+ MB

In [586]:
df.isnull().sum()

flight_id               0
airline                 0
flight_date            35
origin                  0
destination             0
scheduled_departure    25
actual_departure       29
scheduled_arrival       0
actual_arrival          0
departure_delay         0
arrival_delay           0
cancelled               0
cancellation_reason     0
flight_distance_km      0
aircraft_type           0
passengers              0
baggage_count           0
weather_condition       0
airport_congestion      0
ticket_price            0
status                  0
dtype: int64

In [587]:
df.loc[:,"status"]=(df["status"].str.strip().str.title())

In [588]:
df["status"].unique()

array(['Delayed', 'On Time', 'Severely Delayed', 'Cancelled'],
      dtype=object)

In [589]:
df["airport_congestion"].unique()

array(['Medium', 'Low', 'High'], dtype=object)

In [590]:
df["weather_condition"].unique()

array(['Cloudy', 'Clear', 'Fog', 'Rain', 'Storm', 'Windy', 'Unknown'],
      dtype=object)

In [591]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8492 entries, 0 to 8599
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   flight_id            8492 non-null   object
 1   airline              8492 non-null   object
 2   flight_date          8457 non-null   object
 3   origin               8492 non-null   object
 4   destination          8492 non-null   object
 5   scheduled_departure  8467 non-null   object
 6   actual_departure     8463 non-null   object
 7   scheduled_arrival    8492 non-null   object
 8   actual_arrival       8492 non-null   object
 9   departure_delay      8492 non-null   object
 10  arrival_delay        8492 non-null   object
 11  cancelled            8492 non-null   bool
 12  cancellation_reason  8492 non-null   object
 13  flight_distance_km   8492 non-null   int64
 14  aircraft_type        8492 non-null   object
 15  passengers           8492 non-null   int64
 16  baggage_count        8492 non-null   int64
 17  weather_condition    8492 non-null   object
 18  airport_congestion   8492 non-null   object
 19  ticket_price         8492 non-null   int64
 20  status               8492 non-null   object
dtypes: bool(1), int64(4), object(16)
memory usage: 1.4+ MB

In [592]:
df["flight_date"].unique()

array(['2025-05-11', '2024-04-25', '2025-03-24', '2025-03-01',
       '2025-01-14', '2025-05-14', '2025-01-04', '2024-05-26',
       '2024-01-14', '28/05/2025', '2025-10-12', '2025-04-02',
       '2024-07-24', '2025-10-08', '2025-11-18', '2025-06-08',
       '2025-05-05', '2025-08-26', nan, '2024-10-23', '2025-01-10',
       '2024-01-21', '2025-06-12', '2025-01-26', '2025-02-27',
       '2024-01-17', '2025-02-11', '2025-12-07', '31/05/2025',
       '2024-01-25', '2024-04-26', '2025-05-13', '2024-07-01',
       '2024-11-17', '2024-12-06', '2024-10-19', '2024-02-29',
       '2024-06-08', '2024-11-14', '2025-02-04', '2025-03-15',
       '2024-06-11', '2025-12-23', '2024-01-07', '2025-02-24',
       '2024-04-20', '2025-02-20', '2025-07-15', '2024-08-18',
       '2024-04-02', '2024-04-17', '2025-01-15', '2024-06-13',
       '2024-09-22', '2024-09-05', '2025-11-07', '2024-10-02',
       '2025-10-07', '2025-12-22', '2025-03-11', '2025-08-23',
       '2024-02-26', '2024-11-29', '2024-07-10', '2025-12-02',
       '2025-06-04', '2025-06-05', '2024-12-16', '2024-11-16',
       '2025-07-12', '2024-07-14', '2025-07-26', '2025-08-08',
       '2025-05-09', '2024-06-22', '2024-05-03', '2024-03-31',
       '2025-10-17', '2025-08-30', '2024-11-09', '2025-04-04',
       '2025-10-19', '2024-11-10', '2025-08-22', '2025-07-05',
       '2025-03-05', '2025-08-12', '2025-08-14', '2024-02-11',
       '2025-06-30', '2024-03-23', '2025-09-04', '2025-07-08',
       '2024-03-25', '2025-06-16', '2025-01-18', '2025-02-10',
       '2024-07-20', '2025-01-29', '2025-10-01', '2024-05-13',
       '2024-09-30', '2024-08-14', '2024-04-11', '2024-05-15',
       '2025-11-02', '2025-01-05', '2025-08-15', '2024-03-13',
       '2024-04-12', '2024-10-17', '2025-09-01', '2024-02-08',
       '2025-04-14', '2025-04-20', '2025-08-29', '25/09/2024',
       '2024-04-15', '2024-07-29', '2025-02-06', '2025-07-14',
       '2025-01-07', '2024-06-15', '2025-11-22', '2025-08-01',
       '2024-07-23', '2025-11-29', '2024-06-26', '2025-04-11',
       '2024-11-05', '2024-04-10', '2024-10-21', '2024-10-27',
       '2024-10-07', '2024-05-17', '2025-04-06', '2024-05-12',
       '2025-10-30', '2025-08-13', '2025-09-07', '2025-11-21',
       '22/05/2024', '2025-06-22', '2024-05-22', '2024-11-07',
       '2025-11-12', '2024-06-04', '2024-02-28', '2025-11-13',
       '2024-08-17', '2025-02-22', '2024-09-11', '2025-10-29',
       '2024-11-22', '2024-01-31', '2024-07-18', '2025-03-29',
       '2025-11-06', '2025-04-05', '2024-08-06', '2025-12-05',
       '2024-03-15', '2025-12-09', '2024-07-31', '2025-10-27',
       '2024-05-10', '2025-06-21', '2024-07-06', '2025-03-03',
       '2025-06-14', '2025-04-15', '2024-03-08', '2024-05-21',
       '2024-09-20', '2025-06-07', '2025-07-25', '2024-10-28',
       '2025-05-01', '2025-12-30', '2025-08-06', '2025-04-30',
       '2025-01-09', '2025-06-25', '2025-05-23', '2025-02-05',
       '2025-08-02', '2024-11-03', '2025-05-15', '2024-03-04',
       '2025-01-16', '2024-01-05', '2025-03-30', '2024-11-01',
       '2025-10-05', '2024-02-24', '2024-06-16', '2024-05-02',
       '2025-09-29', '22/08/2024', '2024-10-01', '2024-08-19',
       '2024-03-12', '2025-05-30', '2025-02-02', '2025-03-17',
       '2025-10-10', '2025-02-17', '2024-09-21', '2024-08-10',
       '2024-07-11', '2025-05-19', '2024-06-30', '2025-06-11',
       '2025-03-06', '2025-09-06', '2024-10-29', '2024-07-27',
       '2024-12-11', '2025-01-19', '2024-08-15', '2025-05-18',
       '2025-12-01', '2025-09-21', '2024-06-19', '2024-06-20',
       '2024-06-05', '2025-09-16', '2025-09-17', '2025-10-21',
       '2024-12-20', '2024-12-23', '2024-12-31', '2024-03-28',
       '06/06/2024', '2025-02-16', '2024-02-21', '2025-01-03',
       '2024-07-05', '2025-07-19', '2025-10-22', '2024-02-12',
       '2024-04-22', '2025-07-04', '2024-09-27', '2024-11-11',
       '2025-12-08', '2024-11-18', '2024-10-18', '2025-04-08',
       '2025-04-16', '2025-01-13', '2025-09-09', '2025-07-03',
       '2024-04-19', '2025-06-13', '2024-02-07', '2024-08-05',
       '2025-06-18', '2025-05-12', '2025-03-28', '2024-01-09',
       '2025-01-22', '2024-12-13', '2024-09-15', '2025-07-07',
       '2025-05-10', '2024-01-19', '2024-04-14', '2025-04-03',
       '2025-11-25', '2024-05-06', '2024-10-16', '2024-08-30',
       '2025-12-17', '2024-08-09', '2025-01-25', '2024-04-03',
       '2024-03-07', '2025-12-28', '2025-11-04', '2025-01-21',
       '2025-01-30', '2025-02-21', '2025-03-27', '2024-04-01',
       '2024-11-24', '09/02/2025', '2025-12-14', '2024-02-14',
       '2025-09-02', '2024-08-28', '2025-10-24', '2025-03-23',
       '2025-02-26', '2024-06-03', '2024-03-24', '2025-07-28',
       '2025-10-18', '2024-06-12', '2024-06-25', '2025-09-15',
       '2024-02-19', '2024-03-16', '2025-11-10', '2024-01-18',
       '2024-07-16', '2025-05-31', '2025-01-12', '2025-05-29',
       '2025-03-16', '2025-07-02', '2025-12-11', '2024-08-13',
       '2024-11-21', '2024-05-01', '2025-04-25', '2025-09-13',
       '2024-08-02', '2024-05-16', '2024-03-09', '23/09/2025',
       '2024-10-31', '2024-12-14', '2024-01-13', '2025-02-13',
       '2024-12-18', '2024-04-23', '2025-08-04', '2025-09-25',
       '2025-11-16', '2025-01-17', '2024-09-10', '2024-01-11',
       '2024-04-30', '2024-01-10', '2024-09-16', '2024-04-08',
       '2025-06-23', '2024-11-15', '2025-08-25', '2024-08-04',
       '2024-03-02', '2025-04-23', '2024-01-06', '2025-07-22',
       '2025-10-15', '2025-12-20', '2024-03-30', '2024-08-25',
       '2024-08-11', '2024-07-08', '2025-09-19', '2024-08-01',
       '2025-03-08', '2024-01-24', '2024-03-21', '2024-10-14',
       '2024-04-13', '2024-03-06', '2024-11-26', '2024-06-21',
       '2024-03-17', '2025-06-02', '2024-05-14', '2025-01-01',
       '2025-09-20', '2024-11-04', '2024-11-25', '2025-09-12',
       '2024-01-12', '2025-08-24', '2025-09-23', '2025-04-26',
       '31/08/2024', '2025-04-28', '2024-07-25', '2024-02-05',
       '2025-08-05', '28/04/2025', '2025-07-21', '2025-04-21',
       '2025-07-11', '2025-05-08', '2025-03-14', '2024-05-05',
       '2025-07-17', '2024-07-03', '2024-06-24', '2025-05-25',
       '2025-11-27', '2024-09-26', '2024-11-02', '2025-06-09',
       '2024-04-18', '2024-09-09', '2025-08-10', '2025-12-29',
       '2024-07-17', '2025-11-03', '2024-08-24', '2025-06-26',
       '2024-09-13', '2024-11-28', '2025-12-13', '2024-05-25',
       '2024-10-10', '2024-12-08', '2025-08-16', '16/05/2024',
       '2024-09-07', '2025-02-12', '18/08/2025', '2024-11-19',
       '2025-06-19', '2025-07-29', '2025-07-18', '2024-12-29',
       '2024-11-30', '2024-09-19', '2024-03-18', '2025-04-09',
       '06/04/2025', '2025-12-19', '2025-05-07', '2024-11-08',
       '2025-03-02', '2024-07-15', '2024-01-26', '05/06/2025',
       '17/09/2024', '2024-09-23', '2025-04-27', '2024-08-21',
       '2025-04-24', '2024-12-22', '2025-06-27', '2024-09-14',
       '2024-11-23', '2024-01-08', '2024-09-12', '2025-11-11',
       '2024-09-25', '2024-01-22', '2025-09-14', '2024-01-04',
       '2025-03-13', '2024-02-03', '2024-12-05', '2024-05-20',
       '2024-02-10', '2025-06-24', '2024-12-04', '2024-07-21',
       '2025-09-22', '2025-03-22', '2025-12-03', '2024-11-06',
       '2024-02-02', '2025-09-08', '2025-11-23', '2024-07-09',
       '2025-11-14', '2024-12-24', '2024-12-26', '2025-06-17',
       '2024-04-21', '2024-06-28', '28/08/2025', '2024-12-12',
       '22/10/2024', '2025-05-22', '2025-07-10', '2025-04-19',
       '2025-10-25', '2024-10-22', '2024-07-26', '2024-06-01',
       '2024-06-10', '2024-01-02', '2024-01-27', '2024-05-28',
       '07/03/2024', '2025-10-20', '2024-09-03', '2024-05-27',
       '2025-03-07', '2024-09-08', '2024-06-14', '2025-01-06',
       '2024-02-17', '2024-02-15', '2025-12-24', '2025-07-09',
       '2024-05-31', '2024-10-09', '14/08/2025', '2024-10-24',
       '2025-08-07', '2024-03-26', '2025-02-01', '2025-02-18',
       '2024-01-29', '2024-06-09', '2024-08-26', '2025-05-06',
       '2025-03-19', '2025-09-18', '2025-04-17', '2025-09-03',
       '2024-01-16', '2024-10-30', '2024-09-02', '2025-08-17',
       '2025-07-01', '2025-08-31', '2024-01-20', '2024-08-16',
       '2025-09-27', '2024-07-04', '2024-06-18', '2025-10-26',
       '2024-08-12', '2024-08-27', '2025-11-09', '2025-06-01',
       '2025-08-11', '12/12/2024', '2024-10-15', '2025-09-24',
       '2025-08-21', '2024-02-27', '2024-11-27', '2024-11-13',
       '2024-05-29', '2024-04-09', '28/10/2025', '2024-08-31',
       '2025-10-23', '2025-11-24', '2025-01-24', '2024-02-22',
       '2025-12-16', '2025-02-19', '2024-03-11', '2024-05-11',
       '2025-12-12', '2025-12-27', '2025-11-01', '2024-08-22',
       '2024-06-17', '2024-12-07', '2025-05-16', '2024-04-05',
       '2025-08-27', '06/08/2024', '2025-09-26', '2025-03-21',
       '2025-01-20', '2025-10-11', '2025-12-31', '2024-09-18',
       '2024-02-18', '2025-01-11', '2025-02-03', '2024-07-30',
       '2025-10-16', '2024-05-24', '2024-10-05', '2024-04-29',
       '2024-03-22', '2024-03-29', '2025-08-20', '2024-05-19',
       '2024-10-13', '2024-05-08', '2025-12-25', '2024-09-24',
       '2024-07-02', '08/05/2025', '2025-01-28', '2025-03-25',
       '2025-11-28', '02/11/2025', '2025-02-07', '2025-04-12',
       '2025-10-02', '25/11/2024', '2025-04-01', '2024-01-03',
       '2025-06-06', '2024-09-06', '2024-12-01', '2025-05-02',
       '2025-05-20', '2024-08-20', '2025-08-09', '2024-03-27',
       '2025-05-04', '2025-04-18', '2024-05-09', '2025-12-21',
       '2025-07-31', '2025-07-30', '2024-01-28', '2024-03-01',
       '2025-11-08', '2025-07-20', '2025-02-23', '2025-05-28',
       '2025-10-09', '2024-02-06', '2025-02-14', '2024-10-06',
       '2024-02-01', '2024-03-20', '2024-02-04', '20/06/2025',
       '2024-04-24', '2024-12-28', '2025-11-15', '16/06/2025',
       '2024-12-21', '2025-07-27', '2025-10-06', '2025-02-28',
       '2024-05-18', '09/12/2025', '2024-04-06', '2024-10-25',
       '09/08/2024', '2025-04-13', '2025-04-29', '2024-04-27',
       '2025-10-13', '2024-04-04', '03/07/2025', '2024-05-23',
       '2025-09-10', '2024-01-01', '2024-12-15', '2025-11-05',
       '2024-06-23', '2025-06-15', '2024-10-12', '2024-09-28',
       '09/08/2025', '2025-08-28', '29/05/2025', '2025-05-26',
       '04/12/2025', '2025-06-10', '2024-12-03', '2025-02-25',
       '2024-08-08', '2025-05-17', '2024-10-08', '2024-09-29',
       '2024-11-20', '2024-01-15', '2024-11-12', '2024-08-29',
       '2024-10-20', '2025-01-23', '27/11/2025', '2025-12-04',
       '2024-08-03', '2024-06-27', '2025-12-18', '2025-02-08',
       '2024-03-19', '2025-03-10', '2025-01-27', '2025-03-12',
       '2024-09-17', '28/10/2024', '2025-06-28', '2024-02-23',
       '2025-06-20', '2024-06-06', '19/04/2024', '2025-10-31',
       '2025-10-14', '2024-05-30', '2025-12-06', '2024-12-09',
       '2025-08-19', '2025-10-28', '2024-12-25', '2024-12-19',
       '2025-03-18', '2025-07-23', '2025-06-03', '2024-12-02',
       '2024-05-04', '2024-12-27', '2024-12-30', '2024-03-10',
       '2025-04-07', '2024-10-26', '2025-02-15', '2024-04-16',
       '31/08/2025', '2025-03-20', '2024-09-04', '2024-08-23',
       '02/03/2024', '2024-12-10', '2024-09-01', '2024-03-14',
       '2024-05-07', '2025-11-17', '2024-10-11', '2025-12-15',
       '15/06/2025', '2024-03-05', '2025-09-30', '2025-08-18',
       '2024-02-09', '08/11/2024', '18/01/2024', '20/02/2024',
       '2025-01-02', '2025-02-09', '2025-05-24', '2024-04-07',
       '2025-05-21', '04/01/2024', '2024-01-30', '2025-05-27',
       '13/06/2025', '20/07/2025', '2024-06-02', '2024-08-07',
       '2024-06-07', '2025-11-30', '2024-06-29', '2025-03-09',
       '2025-06-29', '2025-07-06', '2025-11-26', '03/04/2025',
       '2024-12-17', '31/01/2024', '2025-03-26', '2024-02-20',
       '2025-03-04', '2025-10-03', '26/02/2024', '2024-10-03',
       '05/03/2025', '2025-10-04', '2025-11-20', '05/08/2025',
       '2025-11-19', '26/08/2024', '2024-07-22', '13/03/2024',
       '2024-02-25', '27/10/2025', '2024-02-16', '2024-07-19',
       '2024-07-13', '2025-09-05', '2024-07-07', '2025-01-08',
       '2025-05-03', '16/10/2025', '13/03/2025', '2025-12-26',
       '02/03/2025', '2025-09-28', '2025-08-03', '04/05/2024',
       '2025-09-11', '23/01/2025', '2025-07-16', '18/04/2024',
       '2025-04-22', '2025-03-31', '2025-04-10', '2025-07-24',
       '2024-04-28', '2024-02-13', '30/06/2025', '19/09/2025',
       '2025-12-10', '30/01/2024', '2024-07-12', '07/08/2025',
       '2025-07-13', '2025-01-31', '25/07/2025', '2024-10-04',
       '25/12/2025', '2024-03-03', '19/05/2025', '18/01/2025',
       '24/03/2025', '20/12/2024', '08/09/2025', '28/05/2024',
       '31/10/2024', '20/10/2024', '2024-07-28', '24/05/2024',
       '01/01/2025', '08/03/2025', '22/04/2025', '21/04/2024',
       '27/12/2024', '10/03/2025', '03/12/2024', '21/05/2025',
       '24/07/2024', '2024-01-23', '22/03/2024', '01/09/2024',
       '26/03/2024', '29/10/2025', '12/10/2024', '09/07/2025',
       '07/07/2024', '06/12/2025', '03/01/2024', '03/06/2025',
       '15/06/2024', '21/03/2024', '06/12/2024', '10/08/2024',
       '27/02/2025', '01/07/2024', '30/04/2025', '05/04/2024',
       '07/11/2025', '08/10/2025', '02/08/2024', '02/05/2025',
       '26/01/2024', '14/03/2024', '10/07/2024', '16/12/2024',
       '10/02/2024', '09/04/2025', '14/02/2024', '26/05/2025',
       '07/03/2025', '29/01/2025', '20/11/2024', '27/05/2025',
       '17/05/2025', '09/07/2024', '20/05/2024', '24/03/2024',
       '30/05/2025', '20/01/2024', '04/08/2024', '02/04/2025',
       '02/01/2025', '22/06/2025', '06/01/2024', '26/04/2025',
       '01/09/2025', '20/09/2025', '09/09/2024', '05/02/2024',
       '11/04/2024', '03/03/2024', '18/08/2024', '15/10/2025',
       '29/08/2025', '28/11/2025', '01/06/2024', '20/11/2025',
       '21/01/2024', '11/12/2024', '24/12/2024', '23/12/2024',
       '18/09/2025', '20/10/2025', '29/04/2025', '04/06/2024',
       '01/12/2025', '30/06/2024', '11/07/2025', '09/03/2024',
       '10/10/2025', '19/12/2024', '26/12/2024', '30/09/2025',
       '10/06/2024', '08/07/2025'], dtype=object)

In [595]:
test_dates = (
    df["flight_date"]
    .astype("string")
    .str.strip()
    .str.replace("/", "-", regex=False)
)

test_dates = pd.to_datetime(
    test_dates,
    format="mixed",
    errors="raise"
)

In [597]:
df["flight_date"]=test_dates

In [598]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8492 entries, 0 to 8599
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   flight_id            8492 non-null   object
 1   airline              8492 non-null   object
 2   flight_date          8457 non-null   datetime64[ns]
 3   origin               8492 non-null   object
 4   destination          8492 non-null   object
 5   scheduled_departure  8467 non-null   object
 6   actual_departure     8463 non-null   object
 7   scheduled_arrival    8492 non-null   object
 8   actual_arrival       8492 non-null   object
 9   departure_delay      8492 non-null   object
 10  arrival_delay        8492 non-null   object
 11  cancelled            8492 non-null   bool
 12  cancellation_reason  8492 non-null   object
 13  flight_distance_km   8492 non-null   int64
 14  aircraft_type        8492 non-null   object
 15  passengers           8492 non-null   int64
 16  baggage_count        8492 non-null   int64
 17  weather_condition    8492 non-null   object
 18  airport_congestion   8492 non-null   object
 19  ticket_price         8492 non-null   int64
 20  status               8492 non-null   object
dtypes: bool(1), datetime64[ns](1), int64(4), object(15)
memory usage: 1.4+ MB

In [599]:
df["scheduled_departure"].unique()

array(['2025-05-11 14:59', '2024-04-25 19:33', '2025-03-24 05:19', ...,
       '2024-05-19 06:15', '2024-11-14 12:27', '23-04-2025 08:55'],
      shape=(8421,), dtype=object)

In [600]:
test_scheduled_departure = pd.to_datetime(
    df["scheduled_departure"]
        .astype("string")
        .str.strip()
        .str.replace("/", "-", regex=False),
    format="mixed",
    errors="raise"
)

In [601]:
df["scheduled_departure"]=test_scheduled_departure

In [602]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8492 entries, 0 to 8599
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   flight_id            8492 non-null   object
 1   airline              8492 non-null   object
 2   flight_date          8457 non-null   datetime64[ns]
 3   origin               8492 non-null   object
 4   destination          8492 non-null   object
 5   scheduled_departure  8467 non-null   datetime64[ns]
 6   actual_departure     8463 non-null   object
 7   scheduled_arrival    8492 non-null   object
 8   actual_arrival       8492 non-null   object
 9   departure_delay      8492 non-null   object
 10  arrival_delay        8492 non-null   object
 11  cancelled            8492 non-null   bool
 12  cancellation_reason  8492 non-null   object
 13  flight_distance_km   8492 non-null   int64
 14  aircraft_type        8492 non-null   object
 15  passengers           8492 non-null   int64
 16  baggage_count        8492 non-null   int64
 17  weather_condition    8492 non-null   object
 18  airport_congestion   8492 non-null   object
 19  ticket_price         8492 non-null   int64
 20  status               8492 non-null   object
dtypes: bool(1), datetime64[ns](2), int64(4), object(14)
memory usage: 1.4+ MB

In [603]:
test_actual_departure = pd.to_datetime(
    df["actual_departure"]
        .astype("string")
        .str.strip()
        .str.replace("/", "-", regex=False),
    format="mixed",
    errors="raise"
)

In [604]:
df["actual_departure"]=test_actual_departure

In [606]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8492 entries, 0 to 8599
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   flight_id            8492 non-null   object
 1   airline              8492 non-null   object
 2   flight_date          8457 non-null   datetime64[ns]
 3   origin               8492 non-null   object
 4   destination          8492 non-null   object
 5   scheduled_departure  8467 non-null   datetime64[ns]
 6   actual_departure     8463 non-null   datetime64[ns]
 7   scheduled_arrival    8492 non-null   object
 8   actual_arrival       8492 non-null   object
 9   departure_delay      8492 non-null   object
 10  arrival_delay        8492 non-null   object
 11  cancelled            8492 non-null   bool
 12  cancellation_reason  8492 non-null   object
 13  flight_distance_km   8492 non-null   int64
 14  aircraft_type        8492 non-null   object
 15  passengers           8492 non-null   int64
 16  baggage_count        8492 non-null   int64
 17  weather_condition    8492 non-null   object
 18  airport_congestion   8492 non-null   object
 19  ticket_price         8492 non-null   int64
 20  status               8492 non-null   object
dtypes: bool(1), datetime64[ns](3), int64(4), object(13)
memory usage: 1.4+ MB

In [607]:
test_scheduled_arrival = pd.to_datetime(
    df["scheduled_arrival"]
        .astype("string")
        .str.strip()
        .str.replace("/", "-", regex=False),
    format="mixed",
    errors="raise"
)

In [608]:
df["scheduled_arrival"]=test_scheduled_arrival

In [609]:
test_actual_arrival = pd.to_datetime(
    df["actual_arrival"]
        .astype("string")
        .str.strip()
        .str.replace("/", "-", regex=False),
    format="mixed",
    errors="raise"
)

In [610]:
df["actual_arrival"]=test_actual_arrival

In [611]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8492 entries, 0 to 8599
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   flight_id            8492 non-null   object
 1   airline              8492 non-null   object
 2   flight_date          8457 non-null   datetime64[ns]
 3   origin               8492 non-null   object
 4   destination          8492 non-null   object
 5   scheduled_departure  8467 non-null   datetime64[ns]
 6   actual_departure     8463 non-null   datetime64[ns]
 7   scheduled_arrival    8492 non-null   datetime64[ns]
 8   actual_arrival       8492 non-null   datetime64[ns]
 9   departure_delay      8492 non-null   object
 10  arrival_delay        8492 non-null   object
 11  cancelled            8492 non-null   bool
 12  cancellation_reason  8492 non-null   object
 13  flight_distance_km   8492 non-null   int64
 14  aircraft_type        8492 non-null   object
 15  passengers           8492 non-null   int64
 16  baggage_count        8492 non-null   int64
 17  weather_condition    8492 non-null   object
 18  airport_congestion   8492 non-null   object
 19  ticket_price         8492 non-null   int64
 20  status               8492 non-null   object
dtypes: bool(1), datetime64[ns](5), int64(4), object(11)
memory usage: 1.4+ MB

In [616]:
df["arrival_delay"].unique()

array(['35', '-25', '49', '56', '63', '26', '-7', '14', '1', '38', '21',
       '-3', 'Unknown', '53', '-17', '-11', '19', '5', '43', '9', '47',
       '-15', '17', '-1', '2', '23', '86', '-21', '-19', '60', '58', '41',
       '30', '-22', '-6', '10', '48', '-16', '104', '46', '65', '-24',
       '31', '85', '7', '18', '27', '12', '-23', '15', '50', '24', '79',
       '8', '40', '-18', '67', '-8', '0', '29', '-9', '-2', '32', '78',
       '96', '-10', '-20', '36', '25', '28', '11', '13', '69', '4', '34',
       '37', '-5', '16', '22', '-12', '55', '6', '74', '45', '70', '68',
       '62', '20', '66', '51', '-14', '77', '84', '75', '61', '52', '-4',
       '33', '3', '76', '39', '-13', '42', '81', '54', '59', '64', '80',
       '44', '102', '73', '107', '97', '83', '57', '71', '82', '113',
       '90', '91', '87', '98', '89', '72', '106', '93', '108', '92',
       '100', '95', '114', '103', '99', '105', '125', '134', '101', '94',
       '88', '109', '122', '111', '120'], dtype=object)

In [615]:
df["departure_delay"]=pd.to_numeric(
    df["departure_delay"],errors="coerce")
df["departure_delay"]=df["departure_delay"].fillna(df["departure_delay"].median())

In [617]:
df["arrival_delay"]=pd.to_numeric(
    df["arrival_delay"],errors="coerce")
df["arrival_delay"]=df["arrival_delay"].fillna(df["arrival_delay"].median())

In [618]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8492 entries, 0 to 8599
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   flight_id            8492 non-null   object
 1   airline              8492 non-null   object
 2   flight_date          8457 non-null   datetime64[ns]
 3   origin               8492 non-null   object
 4   destination          8492 non-null   object
 5   scheduled_departure  8467 non-null   datetime64[ns]
 6   actual_departure     8463 non-null   datetime64[ns]
 7   scheduled_arrival    8492 non-null   datetime64[ns]
 8   actual_arrival       8492 non-null   datetime64[ns]
 9   departure_delay      8492 non-null   float64
 10  arrival_delay        8492 non-null   float64
 11  cancelled            8492 non-null   bool
 12  cancellation_reason  8492 non-null   object
 13  flight_distance_km   8492 non-null   int64
 14  aircraft_type        8492 non-null   object
 15  passengers           8492 non-null   int64
 16  baggage_count        8492 non-null   int64
 17  weather_condition    8492 non-null   object
 18  airport_congestion   8492 non-null   object
 19  ticket_price         8492 non-null   int64
 20  status               8492 non-null   object
dtypes: bool(1), datetime64[ns](5), float64(2), int64(4), object(9)
memory usage: 1.4+ MB

In [619]:
df["airport_congestion"].unique()

array(['Medium', 'Low', 'High'], dtype=object)

In [620]:
df.to_csv("final_airline_cleaned.csv",index=False)

In [622]:
import os
os.path.exists("final_airline_cleaned.csv")

True